# Generated by Django 5.1.4 on 2024-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Roll_Number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
